version: '3.1'

services:
  db:
    container_name: PantauKPU
    image: percona:5.7
    restart: always
    command: mysqld --sql_mode=""
    ports:
      - ${DB_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
    - pantaukpu:/var/lib/mysql

volumes:
  pantaukpu:

# SQL_MODE: ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION 